export type LegalDocument = {
  title: string;
  effectiveDate: string;
  version: string;
  introduction: string[];
  sections: Array<{
    id: string;
    title: string;
    paragraphs: string[];
    bullets?: string[];
  }>;
};

export const privacyDocument: LegalDocument = {
  title: 'Privacy Policy',
  effectiveDate: 'May 12, 2026',
  version: 'v1.0',
  introduction: [
    'Landit values the privacy of its users and has established and published this Privacy Policy to comply with applicable data protection laws.',
    'This policy explains the categories of personal information processed in the English conversation practice and AI feedback service provided by Landit, how it is used, how it is stored and destroyed, and the rights available to users.',
  ],
  sections: [
    {
      id: 'collection',
      title: '1. Personal Information We Collect',
      paragraphs: [
        'Landit may process the following information in order to provide the service.',
      ],
      bullets: [
        'Social login information: provider, social account identifier, nickname, email',
        'Service usage information: selected scenarios, conversation history, speech recognition results, feedback results',
        'Voice processing information: voice files submitted during conversation practice are temporarily transmitted and processed for speech recognition and feedback generation.',
        'Device and log information: access time, browser/device environment, error logs, service usage events',
        'Authentication information: access token, refresh token, and session information used to keep you signed in',
      ],
    },
    {
      id: 'purpose',
      title: '2. Purpose of Use',
      paragraphs: [
        'The information we collect is used to provide Landit’s core features and to operate the service securely.',
      ],
      bullets: [
        'Identifying members, maintaining login sessions, and preventing misuse',
        'Running AI conversation practice, speech recognition, and conversation feedback',
        'Improving service quality, analyzing errors, and reviewing usage statistics',
        'Responding to member inquiries and delivering notices',
      ],
    },
    {
      id: 'voice-data',
      title: '3. Processing of Voice Data',
      paragraphs: [
        'Landit processes voice submitted by users during conversation practice in order to convert it into text and to provide an assessment of comprehension and better ways of expressing the utterance.',
        'Landit does not currently retain original voice files for separate storage purposes. Voice files are used temporarily during processing for speech recognition, conversation context analysis, and AI feedback generation.',
        'Usage records such as the text generated by speech recognition, comprehension scores, feedback results, and recording duration may be stored to provide learning results and improve service quality.',
      ],
      bullets: [
        'Original voice files are processed solely to convert the user’s utterance into text and generate feedback.',
        'Original voice files are not used for advertising, user identification, or sale to third parties.',
        'Where possible, analysis for service improvement uses statistical or de-identified data that cannot directly identify an individual.',
        'Upon account deletion, conversation history, speech recognition results, and feedback results linked to the account are deleted or anonymized in accordance with this Privacy Policy.',
      ],
    },
    {
      id: 'retention',
      title: '4. Retention and Destruction',
      paragraphs: [
        'When account deletion is completed, account identification information and social connection information are deleted or anonymized. However, information that must be retained under applicable laws may be stored separately for the prescribed period.',
      ],
      bullets: [
        'Refresh tokens are discarded upon logout or account deletion.',
        'Original voice files are not stored separately and are not retained as a service storage item after processing is complete.',
        'De-identified statistics needed for service quality analysis may be retained in a form that cannot identify an individual.',
        'Information whose statutory retention period has passed is deleted in an unrecoverable manner.',
      ],
    },
    {
      id: 'third-party',
      title: '5. Third-Party Services and Processing Outsourcing',
      paragraphs: [
        'Landit may use external services to the extent necessary for operating the service, such as login, infrastructure operation, voice processing, and AI feedback.',
      ],
      bullets: [
        'Social login provider: Google',
        'Service infrastructure: web hosting, servers, databases, storage',
        'AI and voice processing: speech recognition, TTS, conversation feedback generation',
        'Usage analytics: statistical processing to improve service stability and quality',
      ],
    },
    {
      id: 'rights',
      title: '6. Your Rights',
      paragraphs: [
        'Users may request to access, correct, delete, or suspend the processing of their personal information. You can log out and delete your account from the My Info page in the app.',
      ],
      bullets: [
        'Account deletion can be done from My Info > Delete Account.',
        'If you sign in again with the same social account after deletion, you may be registered as a new member.',
        'Revoking the app’s access to your social account itself can be done separately in each provider’s account settings.',
      ],
    },
    {
      id: 'contact',
      title: '7. Contact',
      paragraphs: [
        'Inquiries regarding personal information can be submitted through the official contact email below.',
        'Contact email: saynowkorea@gmail.com',
      ],
    },
  ],
};

export const termsDocument: LegalDocument = {
  title: 'Terms of Service',
  effectiveDate: 'May 12, 2026',
  version: 'v1.0',
  introduction: [
    'These Terms set out the conditions and procedures for using the English conversation practice and AI feedback service provided by Landit, as well as the rights and obligations of users and the service operator.',
    'By using the service, users are deemed to have reviewed and agreed to these Terms.',
  ],
  sections: [
    {
      id: 'service',
      title: '1. Purpose of the Service',
      paragraphs: [
        'Landit is a learning service that helps users practice English conversation situations and receive feedback on what they say.',
      ],
    },
    {
      id: 'account',
      title: '2. Sign-Up and Accounts',
      paragraphs: [
        'Users may sign up using a social login method provided by Landit, such as Google. Users must keep their accounts secure and may not use another person’s account.',
      ],
      bullets: [
        'The login method may change in line with policy changes by the social login provider.',
        'Upon account deletion, service usage records and account information are deleted or anonymized in accordance with the Privacy Policy.',
      ],
    },
    {
      id: 'usage',
      title: '3. User Obligations',
      paragraphs: [
        'Users must use the service in a manner consistent with its normal learning purpose.',
      ],
      bullets: [
        'Do not infringe on the rights or personal information of others.',
        'Do not interfere with service operation or repeatedly send abnormal requests.',
        'Do not submit illegal or inappropriate voice, text, or content.',
      ],
    },
    {
      id: 'ai',
      title: '4. Nature of AI Feedback',
      paragraphs: [
        'Landit’s AI feedback is reference information intended to support English learning. Voice submitted by users may be used for text conversion, conversation context analysis, and feedback generation. Feedback content may vary depending on actual communication situations, intonation, ambient noise, and speech recognition results.',
      ],
      bullets: [
        'AI feedback does not replace professional interpretation, test scoring, or official certification assessments.',
        'Speech recognition results may differ from the actual utterance, in which case the feedback may also differ.',
        'Users should use the feedback as a learning reference.',
      ],
    },
    {
      id: 'change',
      title: '5. Changes to and Suspension of the Service',
      paragraphs: [
        'Landit may improve features or change some features in order to provide a stable service. Service use may be temporarily restricted due to maintenance, failures, or issues with external services.',
      ],
    },
    {
      id: 'withdrawal',
      title: '6. Logout and Account Deletion',
      paragraphs: [
        'Users can log out or delete their account from the My Info page. When account deletion is completed, the account is deactivated, and related information is deleted or anonymized in accordance with the Privacy Policy.',
      ],
    },
    {
      id: 'liability',
      title: '7. Inquiries and Limitation of Liability',
      paragraphs: [
        'Inquiries arising during use of the service can be submitted through the official contact email (saynowkorea@gmail.com). Landit may limit its liability for indirect damages arising from use of the service to the extent permitted by applicable law.',
      ],
    },
  ],
};
